//! Token definitions for the AGENT‑SEED v15.2 language.
//!
//! Every token carries its kind, original source text, and a byte‑span
//! for use with `miette` diagnostic reporting.

use miette::SourceSpan;
use std::fmt;

// ── Token ──

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Token {
    pub kind: TokenKind,
    pub text: String,
    pub span: SourceSpan,
}

impl Token {
    pub fn new(kind: TokenKind, text: impl Into<String>, start: usize, end: usize) -> Self {
        Self { kind, text: text.into(), span: (start..end).into() }
    }
}

// ── Token kind ──

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    // ── Keywords – S0 (core) ─────────────────────────────────
    KwAgent,
    KwAsk,
    KwAsync,
    KwAwait,
    KwBorrow,
    KwBreak,
    KwCatch,
    KwCognitive,
    KwCompose,
    KwConfident,
    KwContinue,
    KwContract,
    KwDeriveSchema,
    KwDischarge,
    KwDream,
    KwEffect,
    KwElse,
    KwEnum,
    KwEvolve,
    KwExport,
    KwExtern,
    KwFn,
    KwFor,
    KwHandler,
    KwHeartbeat,
    KwIf,
    KwImpl,
    KwIn,
    KwInfer,
    KwInherit,
    KwInterval,
    KwLet,
    KwLoop,
    KwMatch,
    KwMemo,
    KwMod,
    KwMove,
    KwMut,
    KwObserve,
    KwOntology,
    KwOptimize,
    KwOrchestrate,
    KwOwn,
    KwPerform,
    KwPipe,
    KwPipeline,
    KwProb,
    KwPub,
    KwReact,
    KwRedirect,
    KwRef,
    KwReturn,
    KwRoute,
    KwRule,
    KwSchema,
    KwSection,
    KwSeed,
    KwSeedlet,
    KwSelect,
    KwSelf,
    KwSignal,
    KwSpawn,
    KwStruct,
    KwThink,
    KwThrow,
    KwTrait,
    KwTrain,
    KwTry,
    KwType,
    KwUncertain,
    KwUnsafe,
    KwUse,
    KwWhile,

    // ── Keywords – S1 (standard agents) ─────────────────────
    KwActOrSleep,
    KwAnchor,
    KwAttestation,
    KwAudit,
    KwCat7,
    KwCoherency,
    KwConsolidate,
    KwCrdt,
    KwDecay,
    KwDecide,
    KwDeep,
    KwDrift,
    KwDual,
    KwEncoder,
    KwEpisodic,
    KwExhaustive,
    KwFast,
    KwFederation,
    KwFluxmem,
    KwFrontier,
    KwFull,
    KwGating,
    KwGovernance,
    KwGrant,
    KwGraph,
    KwGround,
    KwGuardrail,
    KwIdentity,
    KwIndexer,
    KwInvalidate,
    KwLayer,
    KwLineage,
    KwLogPhase,
    KwMasterAgent,
    KwMemory,
    KwMemoryCycle,
    KwMerkleProof,
    KwMesi,
    KwMesh,
    KwMonitor,
    KwNeurosymbolic,
    KwPrism,
    KwProbe,
    KwProjection,
    KwPrompt,
    KwPrune,
    KwPublish,
    KwQuery,
    KwRecv,
    KwReflection,
    KwReinforce,
    KwRemix,
    KwRequires,
    KwResolve,
    KwRetriever,
    KwReview,
    KwRevoke,
    KwSend,
    KwSlm,
    KwSleep,
    KwStigmergy,
    KwSubscribe,
    KwSvaf,
    KwSystem1,
    KwSystem2,
    KwTemplate,
    KwTick,
    KwTier,
    KwTraverse,
    KwTriPath,
    KwUpdateMemory,
    KwValidate,
    KwVectorClock,
    KwVerifyIdentity,
    KwWriteJournal,

    // ── Keywords – S2 (advanced agents) ─────────────────────
    KwApprove,
    KwCurriculum,
    KwEvolutionary,
    KwPolicy,
    KwReward,
    KwSimulate,
    KwVote,

    // ── Keywords – S3 (kernel) ──────────────────────────────
    KwCorrigible,
    KwDeadSwitch,
    KwDeference,
    KwLowImpact,
    KwSafePark,
    KwSwitchPreservation,
    KwTruthfulness,
    KwZkvm,

    // ── Literals ────────────────────────────────────────────
    Ident,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    RawStringLiteral,
    CharLiteral,
    TrueLiteral,
    FalseLiteral,
    NullLiteral,
    ProbabilityLiteral,
    IntervalLiteral,
    DidLiteral,

    // ── Operators & punctuation ─────────────────────────────
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Eq,
    EqEq,
    NotEq,
    Lt,
    Gt,
    LtEq,
    GtEq,
    Not,
    And,
    AndAnd,
    Or,
    OrOr,
    Caret,
    Tilde,
    Shl,
    Shr,
    Arrow,
    FatArrow,
    Dot,
    DotDot,
    DotDotEq,
    Colon,
    ColonColon,
    Semicolon,
    Comma,
    At,
    Question,
    Hash,
    Dollar,
    Backslash,
    // ── Compound operators (v15) ──────────────────────────
    TildeGt,          // ~>  mesh send
    LtTilde,          // <~  mesh recv
    ColonColonColon,  // ::: ontology constraint
    AtAt,             // @@  federation publish
    QuestionExcl,     // ?!  confidence gate

    // ── Brackets ────────────────────────────────────────────
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,

    // ── Pipeline / redirection operators ───────────────────
    Pipe,
    PipeGt,
    PipeGtGt,
    PipeAnd,
    RedirectOut,
    RedirectAppend,
    RedirectIn,
    RedirectErr,

    // ── Compound assignment ────────────────────────────────
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    AndEq,
    OrEq,
    CaretEq,
    ShlEq,
    ShrEq,

    // ── Misc ───────────────────────────────────────────────
    Eof,
    Error,
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

// ── Helper: check if a keyword string matches ──
pub fn keyword_from_str(word: &str) -> Option<TokenKind> {
    Some(match word {
        // S0
        "agent"            => TokenKind::KwAgent,
        "ask"              => TokenKind::KwAsk,
        "async"            => TokenKind::KwAsync,
        "await"            => TokenKind::KwAwait,
        "borrow"           => TokenKind::KwBorrow,
        "break"            => TokenKind::KwBreak,
        "catch"            => TokenKind::KwCatch,
        "cognitive"        => TokenKind::KwCognitive,
        "compose"          => TokenKind::KwCompose,
        "confident"        => TokenKind::KwConfident,
        "continue"         => TokenKind::KwContinue,
        "contract"         => TokenKind::KwContract,
        "derive_schema"    => TokenKind::KwDeriveSchema,
        "discharge"        => TokenKind::KwDischarge,
        "dream"            => TokenKind::KwDream,
        "effect"           => TokenKind::KwEffect,
        "else"             => TokenKind::KwElse,
        "enum"             => TokenKind::KwEnum,
        "evolve"           => TokenKind::KwEvolve,
        "export"           => TokenKind::KwExport,
        "extern"           => TokenKind::KwExtern,
        "fn"               => TokenKind::KwFn,
        "for"              => TokenKind::KwFor,
        "handler"          => TokenKind::KwHandler,
        "heartbeat"        => TokenKind::KwHeartbeat,
        "if"               => TokenKind::KwIf,
        "impl"             => TokenKind::KwImpl,
        "in"               => TokenKind::KwIn,
        "infer"            => TokenKind::KwInfer,
        "inherit"          => TokenKind::KwInherit,
        "interval"         => TokenKind::KwInterval,
        "let"              => TokenKind::KwLet,
        "loop"             => TokenKind::KwLoop,
        "match"            => TokenKind::KwMatch,
        "memo"             => TokenKind::KwMemo,
        "mod"              => TokenKind::KwMod,
        "move"             => TokenKind::KwMove,
        "mut"              => TokenKind::KwMut,
        "observe"          => TokenKind::KwObserve,
        "ontology"         => TokenKind::KwOntology,
        "optimize"         => TokenKind::KwOptimize,
        "orchestrate"      => TokenKind::KwOrchestrate,
        "own"              => TokenKind::KwOwn,
        "perform"          => TokenKind::KwPerform,
        "pipe"             => TokenKind::KwPipe,
        "pipeline"         => TokenKind::KwPipeline,
        "prob"             => TokenKind::KwProb,
        "pub"              => TokenKind::KwPub,
        "react"            => TokenKind::KwReact,
        "redirect"         => TokenKind::KwRedirect,
        "ref"              => TokenKind::KwRef,
        "return"           => TokenKind::KwReturn,
        "route"            => TokenKind::KwRoute,
        "rule"             => TokenKind::KwRule,
        "schema"           => TokenKind::KwSchema,
        "section"          => TokenKind::KwSection,
        "seed"             => TokenKind::KwSeed,
        "seedlet"          => TokenKind::KwSeedlet,
        "select"           => TokenKind::KwSelect,
        "self"             => TokenKind::KwSelf,
        "signal"           => TokenKind::KwSignal,
        "spawn"            => TokenKind::KwSpawn,
        "struct"           => TokenKind::KwStruct,
        "think"            => TokenKind::KwThink,
        "throw"            => TokenKind::KwThrow,
        "trait"            => TokenKind::KwTrait,
        "train"            => TokenKind::KwTrain,
        "try"              => TokenKind::KwTry,
        "type"             => TokenKind::KwType,
        "uncertain"        => TokenKind::KwUncertain,
        "unsafe"           => TokenKind::KwUnsafe,
        "use"              => TokenKind::KwUse,
        "while"            => TokenKind::KwWhile,

        // S1
        "act_or_sleep"     => TokenKind::KwActOrSleep,
        "anchor"           => TokenKind::KwAnchor,
        "attestation"      => TokenKind::KwAttestation,
        "audit"            => TokenKind::KwAudit,
        "cat7"             => TokenKind::KwCat7,
        "coherency"        => TokenKind::KwCoherency,
        "consolidate"      => TokenKind::KwConsolidate,
        "crdt"             => TokenKind::KwCrdt,
        "decay"            => TokenKind::KwDecay,
        "decide"           => TokenKind::KwDecide,
        "deep"             => TokenKind::KwDeep,
        "drift"            => TokenKind::KwDrift,
        "dual"             => TokenKind::KwDual,
        "encoder"          => TokenKind::KwEncoder,
        "episodic"         => TokenKind::KwEpisodic,
        "exhaustive"       => TokenKind::KwExhaustive,
        "fast"             => TokenKind::KwFast,
        "federation"       => TokenKind::KwFederation,
        "fluxmem"          => TokenKind::KwFluxmem,
        "frontier"         => TokenKind::KwFrontier,
        "full"             => TokenKind::KwFull,
        "gating"           => TokenKind::KwGating,
        "governance"       => TokenKind::KwGovernance,
        "grant"            => TokenKind::KwGrant,
        "graph"            => TokenKind::KwGraph,
        "ground"           => TokenKind::KwGround,
        "guardrail"        => TokenKind::KwGuardrail,
        "identity"         => TokenKind::KwIdentity,
        "indexer"          => TokenKind::KwIndexer,
        "invalidate"       => TokenKind::KwInvalidate,
        "layer"            => TokenKind::KwLayer,
        "lineage"          => TokenKind::KwLineage,
        "log"              => TokenKind::KwLogPhase,
        "master_agent"     => TokenKind::KwMasterAgent,
        "memory"           => TokenKind::KwMemory,
        "memory_cycle"     => TokenKind::KwMemoryCycle,
        "merkle_proof"     => TokenKind::KwMerkleProof,
        "mesi"             => TokenKind::KwMesi,
        "mesh"             => TokenKind::KwMesh,
        "monitor"          => TokenKind::KwMonitor,
        "neurosymbolic"    => TokenKind::KwNeurosymbolic,
        "prism"            => TokenKind::KwPrism,
        "probe"            => TokenKind::KwProbe,
        "projection"       => TokenKind::KwProjection,
        "prompt"           => TokenKind::KwPrompt,
        "prune"            => TokenKind::KwPrune,
        "publish"          => TokenKind::KwPublish,
        "query"            => TokenKind::KwQuery,
        "recv"             => TokenKind::KwRecv,
        "reflection"       => TokenKind::KwReflection,
        "reinforce"        => TokenKind::KwReinforce,
        "remix"            => TokenKind::KwRemix,
        "requires"         => TokenKind::KwRequires,
        "resolve"          => TokenKind::KwResolve,
        "retriever"        => TokenKind::KwRetriever,
        "review"           => TokenKind::KwReview,
        "revoke"           => TokenKind::KwRevoke,
        "send"             => TokenKind::KwSend,
        "slm"              => TokenKind::KwSlm,
        "sleep"            => TokenKind::KwSleep,
        "stigmergy"        => TokenKind::KwStigmergy,
        "subscribe"        => TokenKind::KwSubscribe,
        "svaf"             => TokenKind::KwSvaf,
        "system1"          => TokenKind::KwSystem1,
        "system2"          => TokenKind::KwSystem2,
        "template"         => TokenKind::KwTemplate,
        "tick"             => TokenKind::KwTick,
        "tier"             => TokenKind::KwTier,
        "traverse"         => TokenKind::KwTraverse,
        "tri_path"         => TokenKind::KwTriPath,
        "update_memory"    => TokenKind::KwUpdateMemory,
        "validate"         => TokenKind::KwValidate,
        "vector_clock"     => TokenKind::KwVectorClock,
        "verify_identity"  => TokenKind::KwVerifyIdentity,
        "write_journal"    => TokenKind::KwWriteJournal,

        // S2
        "approve"          => TokenKind::KwApprove,
        "curriculum"       => TokenKind::KwCurriculum,
        "evolutionary"     => TokenKind::KwEvolutionary,
        "policy"           => TokenKind::KwPolicy,
        "reward"           => TokenKind::KwReward,
        "simulate"         => TokenKind::KwSimulate,
        "vote"             => TokenKind::KwVote,

        // S3
        "corrigible"          => TokenKind::KwCorrigible,
        "dead_switch"         => TokenKind::KwDeadSwitch,
        "deference"           => TokenKind::KwDeference,
        "low_impact"          => TokenKind::KwLowImpact,
        "safe_park"           => TokenKind::KwSafePark,
        "switch_preservation" => TokenKind::KwSwitchPreservation,
        "truthfulness"        => TokenKind::KwTruthfulness,
        "zkvm"                => TokenKind::KwZkvm,

        // Literals
        "true"             => TokenKind::TrueLiteral,
        "false"            => TokenKind::FalseLiteral,
        "null"             => TokenKind::NullLiteral,
        _ => return None,
    })
}